plugins:
  - name: solidity
  - name: foundry
  - name: fantom
  - name: alchemy

contracts_folder: contracts

networks:
  custom:
    - name: sonictest
      chain_id: 57054
      ecosystem: fantom
      base_ecosystem_plugin: ethereum
    - name: sonic
      chain_id: 146
      ecosystem: fantom
      base_ecosystem_plugin: ethereum

node:
  fantom:
    sonictest:
      uri: https://rpc.blaze.soniclabs.com
    sonic:
      uri: https://rpc.soniclabs.com
    opera:
      uri: https://rpc.ftm.tools

default_ecosystem: ethereum

ethereum:
  default_network: local
  local:
    default_provider: test

fantom:
  default_network: sonictest
  sonictest:
    default_provider: node
    required_confirmations: 2
  sonic:
    default_provider: node
    required_confirmations: 2

solidity:
  evm_version: paris
  via_ir: True

dependencies:
  - name: OAppEvm
    npm: "@layerzerolabs/oapp-evm"
    version: v0.3.0
