plugins:
  - name: solidity
  - name: foundry
  - name: fantom
  - name: alchemy

contracts_folder: contracts

networks:
  custom:
    - name: sonictest
      chain_id: 57054
      ecosystem: fantom
      base_ecosystem_plugin: ethereum

node:
  fantom:
    sonictest:
      uri: https://rpc.blaze.soniclabs.com

default_ecosystem: ethereum

ethereum:
  default_network: local
  local:
    default_provider: test

fantom:
  default_network: sonictest
  sonictest:
    default_provider: node

solidity:
  evm_version: paris

dependencies:
  - name: OAppEvm
    npm: "@layerzerolabs/oapp-evm"
    version: v0.3.0
