[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
via_ir = true

[rpc_endpoints]
sonic = "${SONIC_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"

[etherscan]
sonic = { key = "${SONICSCAN_API_KEY}" }
fantom = { key = "${FTMSCAN_API_KEY}" }
