[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
via_ir = true
evm_version = "paris"

[rpc_endpoints]
sonic = "${SONIC_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"

[etherscan]
sonic = { key = "${SONICSCAN_API_KEY}", chain = 146, url = "${SONICSCAN_URL}"}
fantom = { key = "${FTMSCAN_API_KEY}", chain = 250, url = "${FTMSCAN_URL}"}
